[expo-ads-admob] Add necessary Android configuration steps to README (#8233)
# Why

I followed all of the instructions in the expo-ads-admob package, but I was seeing this error when debugging in Android Studio:
```
java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 

******************************************************************************
* The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
* should follow the instructions here: https://goo.gl/fQ2neu to add a valid  *
* App ID inside the AndroidManifest. Google Ad Manager publishers should     *
* follow instructions here: https://goo.gl/h17b6x.                           *
******************************************************************************
```

It seems like we should update the README.md to let users know to include their AdMob app ID in their Android manifest file. This should probably be merged with the sdk-36 branch too, since that's the branch that is linked to from the [Expo Admob API reference](https://docs.expo.io/versions/latest/sdk/admob/).

# How

I plan to fix this issue with this pull request and also with a merge to the sdk-36 branch.

# Test Plan

Adding this element to my Android manifest file resolved the error.