feat(cli): improve offline support (#22961)
# Why

Offline support is sometimes needed in parts of other commands besides
`start`, this PR introduces an `EXPO_OFFLINE` env var which can be
generally used to force offline support.
<!--
Please describe the motivation for this PR, and link to relevant GitHub
issues, forums posts, or feature requests.
-->

# How

- `EXPO_OFFLINE`
- Show a better error message when your computer is connected to wifi
but there's no signal.
- Assert in `npx expo login` and `npx expo register` when `EXPO_OFFLINE`
is set.
- Fail better when validating versions offline.

In the case of running `npx expo` without wifi:

## Before

```
june-16 𝝠 nexpo               
Starting project at /Users/evanbacon/Documents/GitHub/lab/june-16
Starting Metro Bundler
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
FetchError: request to https://api.expo.dev/v2/versions/latest failed, reason: getaddrinfo ENOTFOUND api.expo.dev
    at ClientRequest.<anonymous> (/Users/evanbacon/Documents/GitHub/expo/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:513:28)
    at TLSSocket.socketErrorListener (node:_http_client:502:9)
    at TLSSocket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

## After

```
june-16 𝝠 nexpo
Starting project at /Users/evanbacon/Documents/GitHub/lab/june-16
Starting Metro Bundler
Unable to reach Expo servers. Falling back to using the cached dependency map (bundledNativeModules.json) from the package "expo" installed in your project.
CommandError: Network connection is unreliable. Try again with the environment variable `EXPO_OFFLINE=1` to skip network requests.
```


<!--
How did you build this feature or fix this bug and why?
-->

# Test Plan

- Updated tests and added new tests for things like the register
command.

---------

Co-authored-by: Expo Bot <34669131+expo-bot@users.noreply.github.com>