[cli] fix js inspector is broken when using web SSG (#23197)
# Why

when web SSG is enabled, pressing `j` to open js inspector is broken:
```
Opening JavaScript inspector in the browser...
Web Bundling complete 4499ms
Web Bundling complete 4524ms
FetchError: invalid json response body at http://192.168.50.38:8081/json/list reason: Unexpected token < in JSON at position 0
FetchError: invalid json response body at http://192.168.50.38:8081/json/list reason: Unexpected token < in JSON at position 0
```

# How

originally we have #21068 fix for the HistoryFallbackMiddleware. the new middleware for SSG unfortunately does not have the fix.
i feel like the root cause is coming from middleware disorder. digging the code in deep, i found we've chained the `connect` app. the `middleware` returned from `Metro.createConnectMiddleware` is actually a connect app, because rn-cli will set the `enhanceMiddleware` and it creates the `connect` app under the hood.

this pr tries to reuse the connect app. without the connect app chaining, those web middlewares will be placed after the inspector proxy middleware.

also removed the #21068 hack for HistoryFallbackMiddleware in this pr.


# Test Plan

```
$ yarn create expo -t tabs@sdk-49 sdk49tabs
$ cd sdk49tabs
$ npx expo start
# press `j`
```

after the fix, i've checked:
1. press `j`
2. check `http://localhost:8081/json/list` returns an array
3. check `http://localhost:8081/helloweb` returns a html content
4. disable SSG (the `"output": "static"` in **app.json**), check `http://localhost:8081/helloweb` returns a html content