[1/n][location][next] Add TypeScript API layer (#49849)
# Why

First PR in the stack that implements `expo-location/next`. It contains
the TypeScript API layer.

# How

Added the TypeScript layer, divided into three directories: `js` -
exposed API with docs, `native` - types defined on the native side; this
folder might be generated with type generation in the future, and
`types` - shared types. This follows the pattern introduced in
`expo-media-library`. It is specifically useful for our use case because
we have a quite complex JS layer, with watchers handled on the JS side.

Adds wrappers around `TaskManager.defineTask` and the watcher
subscription, so that the user does not have to provide a task or
listener name:

```js
defineLocationTask({
  onPosition: (position) => console.log(position.coordinates),
  onError: (error) => console.warn(error.message),
});

const handle = Location.watchPosition({
  profile: LocationProfile.FITNESS,
  onPosition: (position) => console.log(position.speed),
  onError: (error) => console.warn(error),
});
```

Adds hooks: `useLocationForegroundPermissions`,
`useLocationBackgroundPermissions`, `useLocationServices`.

```js
const [permission, requestPermission] = useLocationForegroundPermissions();
const [enabled, enable] = useLocationServices();
```

# Test Plan

Added an NCL screen.

---------

Co-authored-by: HubertBer <bernackihubert03@gmail.com>