[jest] Ignore transforming react-native-reanimated/plugin
Why
---
We use Jest projects to run multi-platform tests. For instance, there is an Android Jest project and an iOS Jest project. Some tests are run under multiple projects, like `test.native.js`. Such tests would cause Jest to fail with:
```
Error: [BABEL]: [BABEL] <path>/expo/node_modules/react-native-reanimated/plugin/index.js: Reentrant plugin detected trying to load "<path>/expo/node_modules/react-native-reanimated/plugin/index.js". This module is not ignored and is trying to load itself while compiling itself, leading to a dependency cycle. We recommend adding it to your "ignore" list in your babelrc, or to a .babelignore. (While processing: <path>/expo/node_modules/react-native-reanimated/plugin/index.js)
```

How
---
Added `'/node_modules/react-native-reanimated/plugin/'` to the `transformIgnorePatterns` setting in the preset defined by `jest-expo`.

Two other small enhancements: added a leading slash to the existing `node_modules`, which more closely matches how Jest's [default rule](https://jestjs.io/docs/configuration#transformignorepatterns-arraystring) is formatted, and replaced a `reduce()` that wasn't reducing with a `flatMap()` call that is mapping.

Test Plan
---
- `jest-expo`'s own tests pass
- Run `yarn test` under `expo-sensors`. Previously it would fail. Now it passes.