[NCL] Remove unused config plugins (#36146)
# Why

Resolves ENG-15460
```
expo run:ios
✖ Prebuild failed
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot append DevMenu module to AppDelegate of language "objcpp"
Error: [ios.dangerous]: withIosDangerousBaseMod: Cannot append DevMenu module to AppDelegate of language "objcpp"
    at /expo/apps/native-component-list/plugins/withDevMenu.js:67:15
```

# How

* Removed unused config plugins
* Removed unsupported arguments
* Updated `expo-modules-test-core` to insert kotlin version in fallback
according to the new template
* Added expo-calendar config plugin to prevent warning


# Test Plan

```sh
(cd templates/expo-template-bare-minimum && npm pack) && cd apps/native-component-list

yarn expo prebuild --template ../../templates/expo-template-bare-minimum/expo-template-bare-minimum-53.0.8.tgz --clean

yarn expo run:ios and yarn expo run:android
```