[filesystem][android] Fix inheritance error in expoview
In expoview, the `ScopedFileSystemModule` and `ScopedFilePermissionModule` classes inherit from `expo-filesystem` classes.
In #14549 the filesystem was kotlinized, but the classes weren't marked as `open`. Without that keyword, Kotlin classes are `final` by default.

This caused errors when building shell-app:  🛠   Building expoview... ❌  Failed to build expoview:
./gradlew exited with non-zero code: 1
Unable to generate manifest from home: Failed to fetch manifest from exp://10.1.0.59:80
/home/runner/work/expo/expo/android/expoview/build/tmp/kapt3/stubs/versionedRelease/versioned/host/exp/exponent/modules/universal/ScopedFileSystemModule.java:6: error: cannot inherit from final FileSystemModule
public final class ScopedFileSystemModule extends expo.modules.filesystem.FileSystemModule {
                                                                         ^/home/runner/work/expo/expo/android/expoview/build/tmp/kapt3/stubs/versionedRelease/versioned/host/exp/exponent/modules/universal/ScopedFilePermissionModule.java:6: error: cannot inherit from final FilePermissionModule
public final class ScopedFilePermissionModule extends expo.modules.filesystem.FilePermissionModule {
                                                                             ^
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':expoview:kaptVersionedReleaseKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution
   > java.lang.reflect.InvocationTargetException (no error message)

This commit marks these classes as `open` to allow them to be inherited from.