[camera] Fix `Caused by java.lang.NoSuchMethodError: No interface method getOrDefault` on Android. (#20921)
# Why

Fixes https://exponent-internal.slack.com/archives/C0238THKESC/p1674158274256649.

# Test Plan

- build and run NCL on Android with SDK 22