[6/n] upgrade to react-native 0.77 - improve 0.76 compatibility (#34078)
# Why

fixes

```
console.error: Could not access feature flag
'enableBridgelessArchitecture' because native
module method
was not available
```

logged by the dev menu - there's incompatibility between JS (built for
77) and native (which can run 76) in
[setUpTimers](https://github.com/facebook/react-native/blame/main/packages/react-native/Libraries/Core/setUpTimers.js).

it's super important to read the feature flags directly from the native
module which is the source of truth, not from the JS wrapping that's
done around it - otherwise incorrect feature flag values are reported
because some of the JS wrapping is evaluated at build time (not run
time).

# How

change reading of the feature flags so that it works for 76 as well as
77.

# Test Plan

`this branch`
new arch: iOS, Android both okay
old arch: iOS okay, Android not tested (hard to build for old arch due
to deps)

when picked to `sdk-52-rn-77` branch
new arch: iOS, Android both okay
old arch: iOS okay, Android okay


# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
-->

- [x] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)