[dev-menu] Fix crash when using hermes on android react-native 0.67 (#16099)
# Why

fix crash when `enableHermes: true` with dev-menu on react-native 0.67. i tested it from bare-expo.
stacktrace:

```
FATAL EXCEPTION: main
Process: dev.expo.payments, PID: 18344
java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
    at com.facebook.react.jscexecutor.JSCExecutor.loadLibrary(JSCExecutor.java:24)
    at com.facebook.react.ReactInstanceManagerBuilder.getDefaultJSExecutorFactory(ReactInstanceManagerBuilder.java:352)
    at com.facebook.react.ReactInstanceManagerBuilder.build(ReactInstanceManagerBuilder.java:319)
    at com.facebook.react.ReactNativeHost.createReactInstanceManager(ReactNativeHost.java:95)
    at expo.modules.devmenu.DevMenuHost.createReactInstanceManager(DevMenuHost.kt:41)
    at com.facebook.react.ReactNativeHost.getReactInstanceManager(ReactNativeHost.java:42)
    at expo.modules.devmenu.DevMenuManager.maybeInitDevMenuHost$lambda-8(DevMenuManager.kt:169)
    at expo.modules.devmenu.DevMenuManager.lambda$rZDvUiNHHHvkcRmdKO265huCv6U(Unknown Source:0)
    at expo.modules.devmenu.-$$Lambda$DevMenuManager$rZDvUiNHHHvkcRmdKO265huCv6U.run(Unknown Source:0)
    at android.os.Handler.handleCallback(Handler.java:938)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:223)
    at android.app.ActivityThread.main(ActivityThread.java:7656)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libjscexecutor.so
    SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/dev.expo.payments/lib-main flags = 1]
    SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/~~ibMyBupkSRJXdt_c772rhw==/dev.expo.payments-ru7gzQ9g2MilqIhz24Lduw==/lib/arm64 flags = 0]
    SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    Native lib dir: /data/app/~~ibMyBupkSRJXdt_c772rhw==/dev.expo.payments-ru7gzQ9g2MilqIhz24Lduw==/lib/arm64
```

the first time to create a `ReactInstanceManager`, it successes. however, the second time to create a `ReactInstanceManager` for dev-menu, it crashes with `NoClassDefFoundError`. it's also uncaughtable [here](https://github.com/facebook/react-native/blob/20b9ed91c02a0cbf2f970bf51ccc4c278c63540c/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java#L348-L354) 

this is because the change landed in react-native 0.67: https://github.com/facebook/react-native/pull/30749

according to jvm spec v2 2.17.5, ([maybe from this spec](https://docs.oracle.com/javase/specs/jvms/se6/html/Concepts.doc.html#24237)). the second time to load a failure class, the vm throws `NoClassDefFoundError`. [there's another reference in android art vm implementation](https://android.googlesource.com/platform/art/+/ec696e5d98ae4c503966f199bac341b50bfa1a5b/runtime/class_linker.cc#478)

# How

for dev-menu, we try to locate `libjsc.so` and create specific javascript executor.

# Test Plan

tested on my react-native 0.67 upgrade branch: https://github.com/expo/expo/pull/16038