[expo-av][web] Fix Video Fullscreen Functions
supportsFullscreenAPI and supportsWebkitFullscreenAPI crash when element is null 

TypeError: Cannot use 'in' operator to search for 'requestFullscreen' in null