[cli]: default web.bundler to metro for new projects (#26452)
# Why

Schema PR: https://github.com/expo/universe/pull/14308

Fulfils part of the requirement of ENG-11084. SDK 50 projects with no
`web.bundler` set, and which do not have `@expo/webpack-config`
installed will default to `metro`.

This changes the error message to

```
CommandError: It looks like you're trying to use web support but don't have the required dependencies installed.

Please install react-native-web@~0.19.6, react-dom@18.2.0 by running:

npx expo install react-native-web@~0.19.6 react-dom@18.2.0

If you're not using web, please ensure you remove the "web" string from the platforms array in the project Expo
config.
```

I"ll update this message in a new PR. Ideally it should just prompt to
user to run `npx expo install`, but that command does not check web
platform dependencies.

# Test Plan



# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).

---------

Co-authored-by: Expo Bot <34669131+expo-bot@users.noreply.github.com>
Co-authored-by: evanbacon <bacon@expo.io>