[home][ncl] fix loading or exporting bundles (#22841)
# Why

fix the following errors when publishing dev home

```
Error: Cannot find module '/Users/kudo/expo/expo/react-native-lab/react-native/rn-get-polyfills'
Require stack:
- /Users/kudo/expo/expo/home/metro.config.js
- /Users/kudo/expo/expo/node_modules/cosmiconfig/node_modules/import-fresh/index.js
- /Users/kudo/expo/expo/node_modules/cosmiconfig/dist/loaders.js
- /Users/kudo/expo/expo/node_modules/cosmiconfig/dist/createExplorer.js
- /Users/kudo/expo/expo/node_modules/cosmiconfig/dist/index.js
- /Users/kudo/expo/expo/node_modules/metro-config/src/loadConfig.js
- /Users/kudo/expo/expo/node_modules/metro-config/src/index.js
- /Users/kudo/expo/expo/node_modules/metro/src/commands/build.js
- /Users/kudo/expo/expo/node_modules/metro/src/index.flow.js
- /Users/kudo/expo/expo/node_modules/metro/src/index.js
- /Users/kudo/expo/expo/packages/@expo/dev-server/build/metro/importMetroFromProject.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/src/export/fork-bundleAsync.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/src/export/createBundles.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/src/export/exportApp.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/src/export/exportAsync.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/src/export/index.js
- /Users/kudo/expo/expo/packages/@expo/cli/build/bin/cli
```

# How

- since the react-native monorepo changes, we should use the `react-native-lab/react-native/packages/react-native` as root.
- republish dev home

# Test Plan

- unversioned expo go + ncl