[expo] Add react-dom to devDependencies of expo (#4082)
# Why

Building `expo` package without `docs` or `apps/native-component-list` present in workspace raised the following error:

```
src/takeSnapshotAsync/captureRef.web.ts:1:29 - error TS2307: Cannot find module 'react-dom'.

1 import { findDOMNode } from 'react-dom';
                              ~~~~~~~~~~~


Found 1 error.
```

This problem occurred when I tried to install dependencies in an Android shell app.

Lets https://github.com/expo/expo/pull/4025 get rid of `{universe,turtle}-package.json`.

# How

I guess if we use `react-dom` in our code (`react-native` too) we should add it to some kind of dependencies, eg. `devDependencies` (where `react-native` is added).

# Test Plan

With this commit installing dependencies in a shell app worked like a charm.