[dev-launcher] Fix useFocusEffect import (#24502)
# Why

Last week while releasing dev-launcher v2.4.11 from the `sdk-49` branch
we encountered this instacrash when using dev-launcher.


![image](https://github.com/expo/expo/assets/11707729/1cb1710f-e4de-4dcb-bb5d-b5bb6d94c96a)

> Error: Couldn't find a navigation object. Is your component inside
NavigationContainer?


This error does not happen on `main`, which makes me think that this
could be related to a different version being resolved by yarn
workspaces?

# How

Updating the `useFocusEffect` import from `@react-navigation/core` to
`@react-navigation/native` fixes this issues on both branches

# Test Plan

Run dev-client through bare-expo on `main` and `sdk-49` (cherry-picked
this commit) branches
<img width="537" alt="image"
src="https://github.com/expo/expo/assets/11707729/055aa706-8e30-4668-ab55-058b9bc1f03a">


# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).