[constants] Fix `expoConfig` be of type `ExpoClientConfig`
`expoConfig` was previosuly of generic `ExpoConfig` and according to docs it's not right (https://docs.expo.dev/versions/latest/sdk/constants/#expoclientconfig)

Moreover it fixes `expo-auth-session` TS error:
```
> et check-packages expo-auth-session
🔍 Checking expo-auth-session package
🏃‍♀️ Running yarn clean
🏃‍♀️ Running yarn build
build script failed, see process output:
stdout > yarn run v1.22.18
stdout > $ expo-module build
stdout > src/SessionUrlProvider.ts(90,78): error TS2339: Property 'hostUri' does not exist on type 'ExpoConfig'.
stdout > info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
stderr > error Command failed with exit code 2.

🏁 0 packages passed, 1 package failed: expo-auth-session
```