Update api-routes.mdx
Fix outdated `@vercel/node` version. Version 3 doesn't support Node v22 and deploying on Vercel throws:
```bash
> Installing Builder: @vercel/node@3.0.11
Exported: dist
Error: Found invalid Node.js Version: "22.x". Please set Node.js Version to 20.x in your Project Settings to use Node.js 20.
Learn More: http://vercel.link/node-version
```

Updating to the latest version fixes the Node error, and allows to deploy with Node v22.