Update setup-native-firebase.md
Since upgrading to Expo SDK 45, I noticed the following error when running my app:

```
❌  (ios/MyApp/AppDelegate.mm:1:1)

> 1 | @import Firebase;
    | ^ use of '@import' when C++ modules are disabled, consider using -fmodules and -fcxx-modules
  2 |
  3 | #import "AppDelegate.h"
  4 |


❌  (ios/MyApp/AppDelegate.mm:36:4)

  34 | - (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
  35 | {
> 36 |   [FIRApp configure];
     |    ^ use of undeclared identifier 'FIRApp'
  37 |   RCTAppSetupPrepareApp(application);
  38 |
  39 |   RCTBridge *bridge = [self.reactDelegate createBridgeWithDelegate:self launchOptions:launchOptions];


› 2 error(s), and 0 warning(s)

Failed to build iOS project. "xcodebuild" exited with error code 65.
```

After doing some research, I came across [this](https://github.com/invertase/react-native-firebase/pull/6223) Pull Request, suggesting to instead import Firebase with `#import <Firebase/Firebase.h>` as opposed to `@import Firebase;`.

I'm not sure exactly how you'd like to handle this or if any documentation needs changing elsewhere but hopefully this is a start, and a little more helpful than an issue.