Update api-routes.mdx
Latest Express requires regex to avoid the following error
```
REPO/node_modules/path-to-regexp/src/index.ts:153
      throw new TypeError(`Missing parameter name at ${i}: ${DEBUG_URL}`);
            ^
TypeError: Missing parameter name at 1: https://git.new/pathToRegexpError
    at name (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:153:13)
    at lexer (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:171:21)
    at lexer.next (<anonymous>)
    at Iter.peek (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:188:32)
    at Iter.tryConsume (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:195:24)
    at Iter.text (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:213:26)
    at consume (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:285:23)
    at parse (/home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:320:18)
    at /home/fabian/repos/Joaia/holoai-monorepo/node_modules/path-to-regexp/src/index.ts:503:40
    at Array.map (<anonymous>)
```