[dev-launcher] Fix crash when using hermes on android react-native 0.67 (#16372)
# Why

Fixes:
```
FATAL EXCEPTION: main
Process: dev.expo.payments, PID: 18344
java.lang.NoClassDefFoundError: com.facebook.react.jscexecutor.JSCExecutor
```

It's turned out that we have to do a similar thing to https://github.com/expo/expo/pull/16099 in `dev-launcher`.

# Test Plan

- run `bare-expo` with Hermes.