[3/n][location][next][iOS] Add getPosition (#50198)
# Why

Implements `getPosition`, which supersedes `getCurrentPositionAsync` and
`getLastKnownLocationAsync` in the new Location API

Uses the new iOS 17+ `liveUpdates` API with configurable profiles

# Design

- All the flitering should be done on the JS side. `timeout` is the
exception: it cannot be implemented solely on the JS side, because we
have to close the updates stream
- `getCurrentPosition` and `getLastKnownPosition` were typically used
together, so we merged them into one `getPosition` function
- `getCurrentPosition` was a misleading contract: we cannot guarantee
that the position is current, it returns whatever the system passes. The
new `maxCachedAge` option makes this explicit
- The way of configuring location update streams differs significantly
between iOS < 17, iOS 17+ and Android. In the new API we mirror the iOS
profiles, so they map 1:1. We also add an additional `lowPower` profile,
which maps to `CLLocationManager` with limited distance accuracy on iOS
and to `LOW_POWER` on Android. We do this because we don't want to opt
out of low power mode on Android, and no modern iOS profile translates
to it 1:1
- It is better to return any position than none at all. That is why,
after the timeout, we still return the cached position even if it
doesn't satisfy `maxCachedAge`. Users should check the timestamp
themselves

# API Shape

```tsx
getPosition(options?: GetPositionOptions): Promise<Position | null>;

type GetPositionOptions = {
  maxCachedAge?: number;
  timeout?: number;
  profile?: LocationProfile;
};
```

# How

* Adds `PositionRequester`, which uses either
`PositionUpdatesLiveSource` or `PositionUpdatesCompatibilitySource`
based on the provided profile
* Added a task group with `group.next()` to handle the timeout
* For `PositionUpdatesLiveSource` we still need `CLLocationManager` to
get the cached value

# Test plan

✅ Added unit tests; tested in BareExpo