Change expo/types export (#35484)
# Why

Installing expo-image in a clean expo app causes a types issue:

```
➜   npx tsc --pretty   
(node:95885) ExperimentalWarning: CommonJS module /opt/homebrew/lib/node_modules/npm/node_modules/debug/src/node.js is loading ES Module /opt/homebrew/lib/node_modules/npm/node_modules/supports-color/index.js using require().
Support for loading ES Module in require() is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
components/ui/IconSymbol.tsx:42:72 - error TS2322: Type 'StyleProp<ViewStyle>' is not assignable to type 'StyleProp<TextStyle>'.
  Type 'ViewStyle' is not assignable to type 'StyleProp<TextStyle>'.
    Type 'ViewStyle' is not assignable to type 'TextStyle'.
      Types of property 'userSelect' are incompatible.
        Type 'string | undefined' is not assignable to type '"text" | "auto" | "none" | "contain" | "all" | undefined'.
          Type 'string' is not assignable to type '"text" | "auto" | "none" | "contain" | "all" | undefined'.

42   return <MaterialIcons color={color} size={size} name={MAPPING[name]} style={style} />;
                                                                          ~~~~~

  node_modules/react-native/Libraries/Text/Text.d.ts:188:3
    188   style?: StyleProp<TextStyle> | undefined;
          ~~~~~
    The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<IconProps<"light" | "title" | "link" | "style" | "accessible" | "filter" | "visibility" | "sort" | "map" | "done" | "scale" | "email" | ... 2221 more ... | "zoom-out-map">, {}, any>> & Pick<...> & InexactPartial<...> & InexactPartial<...>'
```

This is caused by a naming conflict between `expo/types` dir and
`expo/types.ts` file.

# How

We move the import from `expo/types` to `expo`, instead renaming the
types to `SomethingType`.

# Test Plan

Tested this fixed the typescript issue.

# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
-->

- [ ] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)