[docs] Update using-sentry.mdx (#28377)
added conditional for enableNativeFramesTracking when in Expo Go

# Why
Cause noobs like myself blindly copy-paste Expo's docs and if the
examples provided in the docs do not work, we give up.

# How
I cross referenced the instructions given by the Expo docs with the ones
given by Sentry:

https://docs.sentry.io/platforms/react-native/performance/instrumentation/expo-router/

# Test Plan
1. Followed the instructions on Expo docs for integrating Sentry with
Expo-Router
2. I was getting the infamous: `Error while fetching native frames:
SentryError: Native is disabled` exception
3. I added conditional native frames tracking as per the Sentry docs's
Expo-Router integration
4. I haz no error

# Checklist

- [] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [X ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).

this is s doc change not a code change :shrug:

---------

Co-authored-by: Brent Vatne <brentvatne@gmail.com>