fix(metro-config): Fix incompatibility with `metro@0.80.10` (#30905)
This fixes a crash due with `TypeError: (0 , sourceMapString_1.default)
is not a function`, which is caused by a change in
`metro/src/DeltaBundler/Serializers/sourceMapString`:
https://github.com/facebook/metro/commit/34148e61200a508923315fbe387b26d1da27bf4b

- Typings have been updated
- Callsites in `@expo/metro-config` have been fixed

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).

---------

Co-authored-by: Expo Bot <34669131+expo-bot@users.noreply.github.com>