[expo-doctor] fix error when fetching schema for unpublished SDK versions  (#28204)
# Why

When you use a canary version of expo (in my case SDK51) and run `npx
expo-doctor@latest` this will give the following error:
```
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
TypeError: Cannot read properties of undefined (reading 'schema')
```

# How

Ideally we still want to check the schema even for canary versions of
the SDK. Unfortunately it seems that there's no schema published for
either SDK51 or or for canary versions. The best alternative is to check
against `UNVERSIONED` in these cases.

# Test Plan

Create a new expo project and install a recent canary version of expo:
```
npx create-expo-app ExpoReproducer
cd ExpoReproducer
npm install expo@canary && npx expo install --fix
```

To reproduce the error:
```
npx expo-doctor@latest
```

To test the new functionality make an
[alias](https://github.com/expo/expo/tree/main/packages/expo-doctor) and
run the updated expo-doctor.

Terminal output before:
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✖ Check Expo config (app.json/ app.config.js) schema
Unexpected error while running 'Check Expo config (app.json/ app.config.js) schema' check:
TypeError: Cannot read properties of undefined (reading 'schema')
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✔ Check native tooling versions
✔ Check that packages match versions required by installed Expo SDK
One or more checks failed, indicating possible issues with the project.
```

Terminal output after:
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check native tooling versions
✔ Check that native modules do not use incompatible support packages
✔ Check that packages match versions required by installed Expo SDK
✔ Check Expo config (app.json/ app.config.js) schema

Didn't find any issues with the project!
```
Terminal output after w/ schema validation error:
```
✔ Check Expo config for common issues
✔ Check package.json for common issues
✔ Check dependencies for packages that should not be installed directly
✔ Check for issues with metro config
✔ Check for common project setup issues
✔ Check npm/ yarn versions
✔ Check that native modules use compatible support package versions for installed Expo SDK
✔ Check for legacy global CLI installed locally
✔ Check that native modules do not use incompatible support packages
✖ Check Expo config (app.json/ app.config.js) schema
✔ Check that packages match versions required by installed Expo SDK
✔ Check native tooling versions

Detailed check results:

Error: Problem validating fields in /Users/leon/workspace/expo-reproducer/app.json. Learn more: https://docs.expo.dev/workflow/configuration/
 • Field: orientation - must be equal to one of the allowed values.
Warning: we could not find a schema for SDK version 51.0.0, used UNVERSIONED schema instead. This is expected when using a canary SDK version.

One or more checks failed, indicating possible issues with the project.
```

Currently there are no automated test for `ExpoConfigSchemaCheck`

# Checklist

- [x] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).

---------

Co-authored-by: Leon <leon@bencom.nl>
Co-authored-by: Expo Bot <34669131+expo-bot@users.noreply.github.com>
Co-authored-by: Keith Kurak <keith.kurak@gmail.com>