[expo-dev-launcher][iOS] fix dev-client compatibility with Reanimated 3.4.0 (#23726)
# Why

Fixes https://github.com/expo/expo/issues/23719

Dev client with Reanimated 3.4.0 fails on compilation error.
```
❌  (node_modules/expo-dev-launcher/ios/EXRCTAppDelegateInterceptor.mm:64:15)

  62 | #if __has_include(<RNReanimated/REAInitializer.h>) \
  63 |   && !RCT_NEW_ARCH_ENABLED
> 64 |   reanimated::REAInitializer(bridge);
     |               ^ no type named 'REAInitializer' in namespace 'reanimated'
  65 | #endif // __has_inclide(<RNReanimated/REAInitializer.h>) && !RCT_NEW_ARCH_ENABLED
  66 | 
  67 |   return [super jsExecutorFactoryForBridge:bridge];
```

# How

In Reanimated 3.4.0 we simplified the initialization process, so the method `reanimated::REAInitializer(bridge)` is no longer required. I added check to determine if the Reanimated version is lower than 3.4.0.

# Test Plan
Run:
```bash
npx create-expo-app dev-client
cd dev-client
npx expo install expo-dev-client
npm install react-native-reanimated@3.4.0
npx expo run:ios
```
And application should lunch without any problems.

# Checklist

- [x] Documentation is up to date to reflect these changes (eg: https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).