Update build.gradle to use annotationProcessor instead of kapt for room
Fixes an error for non admin users running build on androids. 

```> Task :expo-updates:kaptDebugKotlin
java.io.FileNotFoundException: C:\WINDOWS\sqlite-3.36.0-93068ff4-a0a7-44a0-bc91-2fc763079ab2-sqlitejdbc.dll.lck (Access is denied)```