Fixed bug in Android permission request
Fixed due to this error
[Unhandled promise rejection: TypeError: _expoBarcodeScanner.BarCodeScanner.requestPermissionsAsync is not a function. (In '_expoBarcodeScanner.BarCodeScanner.requestPermissionsAsync()', '_expoBarcodeScanner.BarCodeScanner.requestPermissionsAsync' is undefined)]