[android] re-version prebuilt so libs from ndk r21 (#20202)
# Why

fix #20114, the stacktrace is:

```
 java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libexpo-gl_abi47_0_0.so caused by: dlopen failed: cannot locate symbol "__emutls_get_address" referenced by "/data/app/~~KGcV1AyhsVIjqOBWgJfVnA==/host.exp.exponent-AM5qArEEPfsW1vl-7d8kHA==/lib/arm64/libexpo-gl_abi47_0_0.so
```

# How

- the expo go apk was generated from our ci, which on linux and uses ndk r21. the final libc__shared.so in apk is from ndk r21. however the prebuilt sdk 47 versioned expo-gl and expo-av libs were generated from my mac m1 machine, which uses ndk r24. the inconsistent ndk versions will cause the `__emutls_get_address` issue.
- the reason of why sdk 46 prebuilt libs don't have the issue is that i added [the code](https://github.com/expo/expo/blob/c72cf4191b3770f019ba07c2d9a667bfc3a90212/packages/expo-gl/android/build.gradle#L88-L93) from sdk-47.
- to prevent further issues, i would unify the ndk version from all platforms. previously react-native needs newer ndk because ndk-build broke on m1 machines. now react-native 0.70 builds the code by cmake, and we don't need this workaround anymore. also, on react-native 0.71, they also use ndk r23 for all platforms.

# Test Plan

- ci passed
- uses local build versioned expo go to load https://snack.expo.dev/@kudochien/basic-gl-usage and tests on android api 33 emulator