[brownfield][cli] treat configuration all and maven local as the defaults (#42914)
# Why

It has been reported that the CLI silently does nothing if
`build:android` is called without passing any repo and any task -
https://github.com/expo/expo/issues/42655.

# How

Since it's not guaranteed that maven local, to which we might want to
default will be configured (if user uses some other repos) we can throw
an error:

```sh
> npx expo-brownfield build:android

Build configuration:
- Verbose: false
- Build type: All
- Brownfield library: brownfield
- Repositories: []
- Tasks: []

Error: At least one task or repository must be specified
```

# Test Plan

- Validated the new error handling manually
- Updated and ensured that E2E tests for the CLI pass

# Checklist

- [X] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).