[payments-stripe] Fix `Cannot find name 'process'` (#13779)
# Why

Fixes:
```
stdout > src/utils/checkArgs.ts(20,7): error TS2591: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
```