[cli] fix activity starting error on android 13 (#22286)
# Why

fix `yarn run android` does not start activity on android 13 from a bare-minimum app
fix #22210
close ENG-8426

# How

from android 13, starting will fail if there are no explicitly matched intent-filters: https://developer.android.com/guide/components/intents-filters#match-intent-filter
on an app from generated from bare-minimum template: `yarn create expo -t bare-minimum` without ever prebuilding. we will start the activity with `android.intent.action.RUN` action, but the app does not register this action and cause an error.
```
Starting: Intent { act=android.intent.action.RUN cmp=com.testapp/.MainActivity }
Error type 3
Error: Activity class {com.testapp/com.testapp.MainActivity} does not exist.
```

this pr tries to remove the `android.intent.action.RUN` given that `-n package/.MainActivity` should be good enough.

# Test Plan

- [x] ci passed
- [x] bare-minimum app on android 13
- [x] bare-minimum app on android 12
- [x] bare-minimum app after prebuild (will start with deep linking because we will generate scheme after prebuild: `adb shell am start -a android.intent.action.VIEW -d com.testapp://expo-development-client/?url=...`)
- [x] npx expo run:android with expo-dev-client (`adb shell am start -a android.intent.action.VIEW -d com.testapp://expo-development-client/?url=...`)
- [x] npx expo start (Expo Go case, `adb shell monkey -p host.exp.exponent -c android.intent.category.LAUNCHER 1` + `adb shell am start -a android.intent.action.VIEW -d exp://192.168.1.1:19000`)