[github] Explicitly add node-gyp to workspace dependencies (#24628)
# Why

In the last few days, our GitHub actions have been failing to install
dependencies using yarn with the following error

> info This package requires node-gyp, which is not currently installed.
Yarn will attempt to automatically install it. If this fails, you can
run "yarn global add node-gyp" to manually install it.
error An unexpected error occurred:
"/Users/runner/work/expo/expo/node_modules/eas-expo-go: Cannot read
properties of undefined (reading 'config')".
info If you think this is a bug, please open a bug report with the
information provided in
"/Users/runner/.config/yarn/global/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation
about this command.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "node-gyp@9.4.0" with binaries:
      - node-gyp
Error: Process completed with exit code 1.

E.g.
https://github.com/expo/expo/actions/runs/6315839036/job/17149213071

Seems that yarn does not wait for `node-gyp` to be completely installed
before trying to execute the next step

# How 

Explicitly add node-gyp to workspace dependencies  
# Test Plan

Make sure CI is green

# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).