[dev-client][splash-screen] Fix error when running with new arch mode on android (#19931)
# Why

when turning on new architecture mode with dev-client, there is a runtime crash:
```
java.lang.AssertionError: TurboModules are enabled, but mTurboModuleRegistry hasn't been set.
```

fixes #19866

# How

- react-native has a singleton flag `ReactFeatureFlags.useTurboModules`. even though we have the `ReactNativeHost` with old architecture mode in dev-menu and dev-launcher, [the underlying `CatalystInstanceImpl` will still fail at the check](https://github.com/facebook/react-native/blob/dac6806559c49b267ce6eb2722c9ff3b9108ead1/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java#L473-L477). the `ReactPackageTurboModuleManagerDelegate.Builder` requires some c++ code, considering we don't support new architecture mode in dev-menu and dev-launcher, this pr uses a workaround to pass the `ReactPackageTurboModuleManagerDelegate.Builder` from MainApplication.

- when running on new architecture mode, there is a NPE in [`FrameLayout.onMeasure`](https://android.googlesource.com/platform/frameworks/base/+/4d07687915b39dd4c241f5d22e1f0bd02e41bff8/core/java/android/widget/FrameLayout.java#193). since splash screen view remove itself in `ViewGroup.OnHierarchyChangeListener`. the child iteration will get null from `getChildAt()`. the pr tries to remove the splash screen view from the next run loop.

# Test Plan

- https://github.com/evelant/test_fabric_eas_build + this pr's patch