[config-plugins] Improve error handling in plugin resolver (#38338)
# Why

This PR tackles an interesting bug where AI-generated configurations
were referencing config plugins that don't actually exist (like
expo-crypto, expo-clipboard, expo-print, expo-share). This was leading
to some unexpected errors.

The core of the issue arises when a package is added to Expo's config
plugin array, but that package *doesn't* actually ship a config plugin.
If that package's main entry point isn't a JavaScript file or the main
entry point imports types or `UnavailabilityError` from
`expo-module-core`, which has `src/index.ts` as `main` field, it could
cause a ".ts UNKNOWN_FILE_EXTENSION" error.

<!--
Please describe the motivation for this PR, and link to relevant GitHub
issues, forums posts, or feature requests.
-->

# How
Since we only handled a very specific case (`error instanceof
SyntaxError`) and threw the error for every other issue, it was very
cryptic and users did not easily understand what was going on. I've
updated the error handling logic in
`resolveConfigPluginFunctionWithInfo` to include more detailed messages
about the underlying errors and potential issues with the plugin
reference. I also added a link to the documentation for further
assistance. The most helpful piece is likely that we now print the
`pluginReference` that caused the issue.

I also removed the redundant`SyntaxError` check and just returning the
generic Error message. I think it contains enough information to be
generally useful, and it makes that function cleaner and a bit more
lightweight and universal.

Fixes #37917

Closes ENG-16728

<!--
How did you build this feature or fix this bug and why?
-->

# Test Plan

<!--
Please describe how you tested this change and how a reviewer could
reproduce your test, especially if this PR does not include automated
tests! If possible, please also provide terminal output and/or
screenshots demonstrating your test/reproduction.
-->

Before | After
-- | --
<img width="1186" alt="Screenshot 2025-07-25 at 14 40 49"
src="https://github.com/user-attachments/assets/df09740c-f6c4-49d6-9645-d36d9c447cb0"
/> | <img width="1029" height="162" alt="Screenshot 2025-08-02 at 10 35
18"
src="https://github.com/user-attachments/assets/bd96660c-a9fb-4084-9c88-2f5e0906b662"
/>

Text:
```bash
PluginError: Unable to resolve a valid config plugin for expo-crypto.
• No "app.plugin.js" file found in expo-crypto: config plugins are typically exported from an "app.plugin.js" file in the package root.
• main export of expo-crypto does not appear to be a config plugin: the following error was thrown when importing /Users/hirbod/Expo/repros/StickerSmash/node_modules/expo-crypto/build/Crypto.js: Unknown file extension ".ts" for /Users/hirbod/Expo/repros/StickerSmash/node_modules/expo-modules-core/src/index.ts ERR_UNKNOWN_FILE_EXTENSION
Verify that expo-crypto includes a config plugin. If it does not, then remove the entry from plugins in your app config file. Learn more: https://docs.expo.dev/guides/config-plugins/
```

# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
-->

- [x] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)