Update properties' type on screenWithProperties (#4053)
The `properties` parameter is now a `{ [key: string]: any }` (like trackWithProperties), instead of a string (this was incorrect).

# Why

I was getting a type check error when trying to implement this method the way the documentation says.

```
src/tracking.ts:34:46 - error TS2345: Argument of type '{ [key: string]: any; }' is not assignable to parameter of type 'string'.
34     Segment.screenWithProperties(screenName, properties);
```

The documentation is correct, but the type definition on the `.ts` was not.
https://docs.expo.io/versions/latest/sdk/segment/#segmentscreenwithpropertiesscreenname-properties

# Test Plan

It's mainly a type check test, cause the code should work anyway. But the unit tests on https://github.com/expo/expo/blob/01a4b9e7390278c2305d803e5308b691dab55eb7/apps/test-suite/tests/Segment.js#L67 are passing, and they are sending an object of key: value.