[sweet][kotlin] Add error chaining (#15798)
# Why

Closes ENG-2803.

# How

Added a `DecoreatedError` and `errorDecorator` helper which allows you to chain multiple exceptions. This allows us to provide more readable error messages. For instance, if we couldn't convert a field in the record, you would an error looking like this:
```
Cannot call `f2` from the `dummy-1`.
caused by: Cannot obtain `0` parameter. Tried to cast `Map` to `expo.modules.kotlin.MyRecord`.
caused by: Cannot create a record of the type: `expo.modules.kotlin.MyRecord`.
caused by: Cannot obtain `string` field. Tried to cast `Number` to kotlin.String`.
caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
```
 instead of:
```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
```

Also, I've changed one important thing. The majority of our API won't reject a Promise, but instead, it will throw an exception. 
This change doesn't affect users, cause we still convert exceptions into promise rejection, but we are doing it in the `KotlinInteropModuleRegistry`. 

> Note:
This PR adds an error chaining only to a method call - not to props. I will do it in a separate PR.

# Test Plan

- unit tests ✅