[expo-contacts][expo-sms] Use separate intent tags for AndroidManifest (#13401)
# Why

After upgrading to Beta SDK 42, I came across the android build error when using `yarn android`:

```
Unable to install /BlahBlahBlah/android/app/build/outputs/apk/debug/app-debug.apk
com.android.ddmlib.InstallException: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl932567260.tmp/base.apk (at Binary XML file line #44): intent tag may have at most one data type.
```