[create-expo-module] Rethrow errors from npm (#32721)
# Why

When faced with issues like https://github.com/expo/expo/issues/32711 or
when developing the new templates I struggled with the logs not being
surfaced.

# How

Removed a setting and formatted an error better.

It now shows this for success:

```
✔ Created the module from template files
✔ Installed module dependencies
✔ Compiled TypeScript files
✔ Initialized the example app
✔ Configured the example app
✔ Prebuilt the example app
✔ Installed dependencies in the example app
✔ Skipped creating an empty Git repository, already within a Git repository

✅ Successfully created Expo module
```

And this for failure:

```
✔ Created the module from template files
✔ Installed module dependencies
✔ Compiled TypeScript files
✔ Initialized the example app
✔ Configured the example app
✔ Prebuilt the example app
✖ Installing dependencies in the example app
Error: npm install exited with non-zero code: 1

Error stack:
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/typescsdfript - Not found
npm error 404
npm error 404  'typescsdfript@^5.1.3' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
npm error A complete log of this run can be found in: /Users/aleqsio/.npm/_logs/2024-11-08T15_16_06_646Z-debug-0.log

    at installDependencies (/Users/aleqsio/Work/Expo/expoA/packages/create-expo-module/build/packageManager.js:15:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/aleqsio/Work/Expo/expoA/packages/create-expo-module/build/createExampleApp.js:72:9
    at async newStep (/Users/aleqsio/Work/Expo/expoA/packages/create-expo-module/build/utils/ora.js:19:16)
    at async createExampleApp (/Users/aleqsio/Work/Expo/expoA/packages/create-expo-module/build/createExampleApp.js:71:5)
    at async Command.main (/Users/aleqsio/Work/Expo/expoA/packages/create-expo-module/build/create-expo-module.js:111:13)
```

# Test Plan

Tested manually.

# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).