[cli][dev-server] fix hermes export sourcemap error (#21022)
# Why

react-native 0.71 (metro 0.73) has some changes which makes our `npx expo export` or `expo-cli publish` breaks when composing hermes source map.

```
Error: Invalid mapping: {"generated":{"line":1,"column":254},"source":"/Users/kudo/expo/expo/node_modules/metro-runtime/src/polyfills/require.js","original":{"line":0,"column":0},"name":null}
```

# How

- for hermes, we should [turn off minification](https://github.com/facebook/react-native/blob/86852f8cb5049f94d60e8a5423daccf0fb23cf84/packages/react-native-gradle-plugin/src/main/kotlin/com/facebook/react/TaskConfiguration.kt#L67)
- also fix an issue that we don't enable `-O` (optimization) for hermes compiler.

# Test Plan

on `home` to run `npx expo export`