[brownfield] improve bundle loading error handling (#42469)
# Why

We should clearly inform the user that the requested bundle cannot be
loaded

# How

This approach implements a simple approach with just throwing an error
with clear message when the bundle can't be loaded, but it can't be
easily extended to e.g. display some fallback view instead. This
solution is brownfield-only and doesn't interact with RN `RCTFatalError`
handling

## Android

For `debug` builds that use bundle from Metro we can have the default
red box from RN (which can't be overwritten), as it pretty clearly
informs about the error:

<img width="437" height="785" alt="image"
src="https://github.com/user-attachments/assets/43b7e430-95f3-4611-b813-e0e3ba6bad97"
/>

For `release` builds we can throw an error with a clear message and list
available bundles:

```
Caused by: java.lang.IllegalStateException: Cannot find `indexx.android.bundle` in the assets
Available JS bundles:
- index.android.bundle
```

(In real-life scenario it would fail about `index.android.bundle` not
being found in the application assets and list some other (or none)
bundle(s) as available)

## iOS

For `debug` builds using bundle from Metro it probably doesn't make sens
to display anything besides the default red box from React Native (which
we cannot simply overwrite), as it pretty clearly informs about the
error:

<img width="486" height="920" alt="image"
src="https://github.com/user-attachments/assets/0fde21a6-bb06-4d6d-aebd-bfc0951b3672"
/>

For `release` builds we can throw a `fatalError` with a clear message
that bundle couldn't be found and list of available bundles:

```
minimaltesterbrownfield/ReactNativeDelegate.swift:29: Fatal error: Cannot find `mainabcd.jsbundle` in the XCFramework bundle
Available JS bundles:
- main.jsbundle
```

(In real-life scenario it would fail about `main.jsbundle` not being
found and list some other (or none) bundle(s) as available)

# Test Plan

Validated using `minimal-tester` on Android and iOS with both debug and
release build types

# Checklist

- [X] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [X] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).