[glass-effect] Added ref type to `GlassContainer` and `GlassView` components (#41799)
# Why

<!--
Please describe the motivation for this PR, and link to relevant GitHub
issues, forums posts, or feature requests.
-->

Passing a ref prop to `GlassView` and `GlassContainer` raises a
TypeScript error:
```
 Property 'ref' does not exist on type 'IntrinsicAttributes & { spacing?: number | undefined; } & ViewProps'.
 ```

# How
Added `RefObject` type to `GlassContainerProps` and `GlassViewProps`.
<!--
How did you build this feature or fix this bug and why?
-->

# Test Plan
```tsx
import { useRef } from 'react';
import { type View } from 'react-native';
import { GlassContainer, GlassView } from 'expo-glass-effect';

function ExampleGlassComponent() {
  const glassContainerRef = useRef<View>(null);
  const glassViewRef = useRef<View>(null);

  return (
    <GlassContainer ref={glassContainerRef}>
      <GlassView ref={glassViewRef} />
    </GlassContainer>
  );
}

```
<!--
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction.
-->

# Checklist

<!--
Please check the appropriate items below if they apply to your diff.
-->

- [x] I added a `changelog.md` entry and rebuilt the package sources according to [this short guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build (eg: updated a module plugin).
- [ ] Conforms with the [Documentation Writing Style Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)