[cli] prevent changes to telemetry from crashing upgrade (#32490)
# Why
Fixes the issue noted in https://github.com/expo/universe/pull/17296,
.e.g, where you'd get an error about `tempy` not being available or
`Error: Cannot find module './flushDetached'`when running `npx expo
install expo@next --fix`.

# How
1. Fix the crash specifically when upgrading to SDK 52 by providing a
blank file so the telemetry flush occurring under the old CLI version
(but with the new version's files on disk) can resolve the import (see
here:
https://github.com/expo/expo/blob/main/packages/%40expo/cli/src/utils/telemetry/clients/RudderDetachedClient.ts#L42-L49)
2. Make the detached telemetry flush code more resilient for future SDK
releases by wrapping the process spawn in a try/catch, so future changes
to telemetry don't crash in this scenario. (it may be smart to backport
this 1-2 versions back)

# Test Plan
Ran the an upgrade from a Node 22 / yarn install as described in the
previous pull request, as well as a Node 20/ npm install, which fails
with `Error: Cannot find module './flushDetached'`. Both installs were
successful under the new version