[expo-local-authentication][android] Handle NPE on authenticate (#10965)
# Why

<!-- 
Please describe the motivation for this PR, and link to relevant GitHub issues, forums posts, or feature requests. 
-->

We're experiencing a couple crashes in production, pointing no a Null Pointer Exception in the authenticate method, when using legacy FingerprintManager compatibility.

Crash parcial stack trace:
```
androidx.core.hardware.fingerprint.FingerprintManagerCompat.authenticate
FingerprintManagerCompat.java, line 35
java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
```


# How

<!-- 
How did you build this feature or fix this bug and why? 
-->

This PR adds handling the NPE, by canceling the promise when this is detected. A similar 

# Test Plan

<!-- 
Please describe how you tested this change and how a reviewer could reproduce your test, especially if this PR does not include automated tests! If possible, please also provide terminal output and/or screenshots demonstrating your test/reproduction. 
-->

This is sometimes reproducible when the app is minimized and resumes before the prompt has a chance to be shown.