fix: don't assume reanimated exists when testing expo-router (#27548)
https://docs.expo.dev/router/installation/ doesn't install reanimated.

# Why


When testing Expo Router, the following error will occur

 FAIL  test/smoke/expo-router-smoke.test.tsx
  ● Test suite failed to run

Cannot find module 'react-native-reanimated' from
'node_modules/expo-router/build/testing-library/mocks.js'

    Require stack:
      node_modules/expo-router/build/testing-library/mocks.js
      node_modules/expo-router/build/testing-library/index.js
      node_modules/expo-router/testing-library.js
      test/smoke/expo-router-smoke.test.tsx

> 1 | import { renderRouter, screen } from
'expo-router/testing-library';
        | ^
      2 | import { View } from 'react-native';
      3 |
      4 | it('my-test', async () => {

at Resolver._throwModNotFoundError
(node_modules/jest-resolve/build/resolver.js:427:11)
at Object.mock
(node_modules/expo-router/src/testing-library/mocks.ts:9:6)
at Object.require
(node_modules/expo-router/src/testing-library/index.tsx:14:1)
at Object.<anonymous> (node_modules/expo-router/testing-library.js:1:52)
      at Object.require (test/smoke/expo-router-smoke.test.tsx:1:1)



Tests fail using the example
https://docs.expo.dev/router/reference/testing/#jest-matchers here.

# How

Ensure `react-native-reanimated` in optional in the testing mock.

# Test Plan

<!--
Please describe how you tested this change and how a reviewer could
reproduce your test, especially if this PR does not include automated
tests! If possible, please also provide terminal output and/or
screenshots demonstrating your test/reproduction.
-->

Applied my patch using `patch-package` and it now works:

```
⋊> ~/C/f/r/example on feat/testing-expo-router ⨯ yarn test                                                                                                                       
 PASS  test/smoke/rntl-smoke.test.tsx
 PASS  test/smoke/expo-router-smoke.test.tsx

Test Suites: 2 passed, 2 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.611 s
```

---------

Co-authored-by: Mark Lawlor <mwlawlor@gmail.com>