fix: don't assume reanimated exists when testing expo-router
https://docs.expo.dev/router/installation/ doesn't install reanimated.

 FAIL  test/smoke/expo-router-smoke.test.tsx
  ● Test suite failed to run

    Cannot find module 'react-native-reanimated' from 'node_modules/expo-router/build/testing-library/mocks.js'

    Require stack:
      node_modules/expo-router/build/testing-library/mocks.js
      node_modules/expo-router/build/testing-library/index.js
      node_modules/expo-router/testing-library.js
      test/smoke/expo-router-smoke.test.tsx

    > 1 | import { renderRouter, screen } from 'expo-router/testing-library';
        | ^
      2 | import { View } from 'react-native';
      3 |
      4 | it('my-test', async () => {

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:427:11)
      at Object.mock (node_modules/expo-router/src/testing-library/mocks.ts:9:6)
      at Object.require (node_modules/expo-router/src/testing-library/index.tsx:14:1)
      at Object.<anonymous> (node_modules/expo-router/testing-library.js:1:52)
      at Object.require (test/smoke/expo-router-smoke.test.tsx:1:1)