[sweet API][Kotlin] Add more information to the exceptions thrown from the prop setter (#18776)
# Why

Decorated all exceptions that were thrown from the prop setter in the `PropSetException` to pass more information to the user. 

# How

Some time ago, I've added an ErrorManagerModule which passes information about failures in prop setters. However, we can provide more data to help users detect problems. 

# Test Plan

Before:
```
java.lang.RuntimeException: setParameters failed
```
Now:
```
expo.modules.kotlin.exception.PropSetException: Cannot set prop 'pictureSize' on view 'class expo.modules.camera.ExpoCameraView'
    → Caused by: java.lang.RuntimeException: setParameters failed
```