[DOCS] Add Metro configuration to documentation that fixes Error: Component auth has not been registered yet when using Firebase JS SDK with SDK 53 (#36616)
# Why

As of React Native 0.79, the Metro bundler has enabled support for the
`exports` field in `package.json` by default. Firebase JS SDK is one of
the libaries that incompatible with this (see #36551)

In projects using Firebase, if you call initializeAuth you will get this
error:
`
Error: Component auth has not been registered yet
`

# How

Updated Metro config in [Using Firebase guide on
docs](https://docs.expo.dev/guides/using-firebase/#configure-metro)

# Test Plan

See preview of using-firebase.mdx

# Checklist

- [ ] I added a `changelog.md` entry and rebuilt the package sources
according to [this short
guide](https://github.com/expo/expo/blob/main/CONTRIBUTING.md#-before-submitting)
- [ ] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).
- [x] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)

---------

Co-authored-by: Aman Mittal <amandeepmittal@live.com>