Fix NPE in updateOrScheduleJob in task manager (#40396)
# Why

We often saw logs on sentry like
```
java.lang.RuntimeException: Unable to start receiver expo.modules.taskManager.TaskBroadcastReceiver: java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.sort(java.util.Comparator)' on a null object reference
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:5672)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2904)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loopOnce(Looper.java:273)
    at android.os.Looper.loop(Looper.java:363)
    at android.app.ActivityThread.main(ActivityThread.java:10060)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
java.lang.NullPointerException: Attempt to invoke interface method 'void java.util.List.sort(java.util.Comparator)' on a null object reference
    at java.util.Collections.sort(Collections.java:207)
    at expo.modules.taskManager.TaskManagerUtils.updateOrScheduleJob(TaskManagerUtils.java:127)
    at expo.modules.taskManager.TaskManagerUtils.scheduleJob(TaskManagerUtils.java:66)
    at expo.modules.location.taskConsumers.LocationTaskConsumer.maybeReportDeferredLocations(LocationTaskConsumer.kt:266)
    at expo.modules.location.taskConsumers.LocationTaskConsumer.didReceiveBroadcast(LocationTaskConsumer.kt:87)
    at expo.modules.taskManager.TaskService.handleIntent(TaskService.java:315)
    at expo.modules.taskManager.TaskBroadcastReceiver.onReceive(TaskBroadcastReceiver.java:15)
    at android.app.ActivityThread.handleReceiver(ActivityThread.java:5663)
    at android.app.ActivityThread.-$$Nest$mhandleReceiver
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2904)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loopOnce(Looper.java:273)
    at android.os.Looper.loop(Looper.java:363)
    at android.app.ActivityThread.main(ActivityThread.java:10060)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:632)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975) 
```

According to the open source android project, getAllPendingJobs can
indeed be null:

https://android.googlesource.com/platform//frameworks/base/+/980636f0a5440a12f5d8896d8738c6fcf2430553/apex/jobscheduler/framework/java/android/app/JobSchedulerImpl.java#137

This however happens in case of RemoteException. So everything migth be
broken anyways. I think it still makes sense to try it, as in the code
below we catch failed job scheduling anyways, if there is a bigge
rproblem with the curren tjob scheduler.