[dev-server] fix inconsistent false alarm for exporting on bare project (#23184)
# Why

fix `npx expo export` or `eas update` error on sdk 49 bare project

```
Error: JavaScript engine configuration is inconsistent between app.json and Android native project.
In app.json: Hermes is enabled
In Android native project: Hermes is not enabled
Please check the following files for inconsistencies:
  - /Users/kudo/sdk49/app.json
  - /Users/kudo/sdk49/android/gradle.properties
  - /Users/kudo/sdk49/android/app/build.gradle
Learn more: https://expo.fyi/hermes-android-config
```

# How

this is a regression from #21067. since we removed the `hermesEnabled` and `expo.jsEngine` in **android/app/build.gradle** entirely, we will hit the inconsistent case at https://github.com/expo/expo/blob/b1418cb83ffa82d94805adef977a8957b8ec6141/packages/%40expo/dev-server/src/HermesBundler.ts#L155-L166.

the whole block is not necessary anymore. it is removed in this pr. since @expo/dev-server is in versioned-cli now, this pr also removes many legacy support checks, that would make the code easier to maintain.

# Test Plan

- ci passed
- test the new @expo/dev-server from a bare project and run `npx expo export`