[cli] fix react devtools launching error (#26550)
# Why

when launching react-devtools from cli on sdk 50, it will crash cli with
the following error:
```
/Users/kudo/sdk50/node_modules/@expo/cli/build/src/start/interface/interactiveActions.js:189
        const url = this.devServerManager.getDefaultDevServer().getReactDevToolsUrl();
                                          ^

TypeError: Cannot read properties of undefined (reading 'getDefaultDevServer')
    at Object.openReactDevToolsAsync [as action] (/Users/kudo/sdk50/node_modules/@expo/cli/build/src/start/interface/interactiveActions.js:189:43)
```

# How

that's a regression from #24650. we should make sure the function point
to valid "this".

# Test Plan

on sdk 50 project and trying to launch react-devtools

# Checklist

- [x] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [x] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [x] This diff will work correctly for `npx expo prebuild` & EAS Build
(eg: updated a module plugin).