[cli][dev-client] Fix legacy accept signature parsing in CLI and don't require in dev client (#21970)
This fixes three interconnected bugs:
1. The header that controls this can be named
`exponent-accept-signature` or `expo-accept-signature`. Not sure of the
history here. This PR makes these consistent. And it might have been
fine to leave this as-is but it's easier to reason about this way IMO.
2. The value of this header is either the string "true" or "false".
`Boolean("false") === true`, so this code was always returning true.
This historically seemed to not matter since all clients (including dev
clients) set this to "true".
3. Dev clients were sending `expo-accept-signature: true` header, which
isn't necessary (dev clients don't need signed manifests since they
don't use scoped modules).

Fixes a portion of
https://linear.app/expo/issue/ENG-6980/fall-back-to-serving-unsigned-manifests-if-a-user-isnt-authorized-to

1. `et gba -n testwat expo-dev-menu expo-dev-client expo-dev-launcher
expo-updates expo-manifests expo-updates-interface`
2. Logged-in to user that owns an account, `eas update:configure`
3. Log out
4. Log in to a different user that is a viewer on that account.
5. Build on android/ios
6. In `packages/@expo/cli` run `nexpo start --dev-client`
7. Before changes, see that it throws
    ```
ApiV2Error: Not authorized. You must have DEVELOPER or above access on
the wschurman account to develop this project, or you may remove the
owner listed in app.json to develop this project under your own account.
    ```
8. After changes, see that it works.

<!--
Please check the appropriate items below if they apply to your diff.
This is required for changes to Expo modules.
-->

- [ ] Documentation is up to date to reflect these changes (eg:
https://docs.expo.dev and README.md).
- [ ] Conforms with the [Documentation Writing Style
Guide](https://github.com/expo/expo/blob/main/guides/Expo%20Documentation%20Writing%20Style%20Guide.md)
- [ ] This diff will work correctly for `expo prebuild` & EAS Build (eg:
updated a module plugin).